openapi: 3.0.2
info:
  title: Данные об аутентификации
  version: 1.0.0
  description: |
    ___
    

servers:
  # Можно задать несколько URL для тестирования на разных серверах
  - url: http://localhost:8080/v1
    description: Основной урл

tags:
  # К тегу привязываются методы. Используется для фильтрации методов и деления на разделы.
  - name: authInfo
    description: Инфо об аутентификации

paths:
  /authInfo:
    post:
      tags:
        - authInfo
      summary: Инфо об аутентификации
      description: В теле передается информация об аутентификации сотрудника в системе
      
      requestBody:
        description: |
          Данные об аутентификации сотрудника. 
          
          **Content-Type: application/json** используется только для визуализации тела запроса в SwaggerUI

          **Content-Type: application/x-www-form-urlencoded** используется для выполнения запросов
        content:
          application/json:
            schema:  
              $ref: "#/components/schemas/reqAuthInfo"
          application/x-www-form-urlencoded:
            schema:  
              $ref: "#/components/schemas/reqAuthInfo"

      responses: 
          '200':
            description: Ok
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/respAuthInfo"
              application/x-www-form-urlencoded:
                schema:  
                  $ref: "#/components/schemas/respAuthInfo"

                
components:
  schemas:
    authInfoObj:
      title: authInfoObj
      type: object
      properties:
        employeeId: 
          type: string
          format: uuid
          description: |
            Идентификатор аутентифицированного сотрудника
        authDate: 
          type: string
          format: date-time
          description: |
            Дата и время аутентификации приведенные к UTC + 0
        

    respAuthInfo:
      title: respAuthInfo
      type: object
      properties:
        result:
          type: object
        errors:
          type: array
          items:
            $ref: "#/components/schemas/error"
        status:
          type: string
          example: SUCCESS / WARNING / ERROR

    reqAuthInfo:
      title: reqAuthInfo
      type: object
      properties:
        request:
          $ref: "#/components/schemas/authInfoObj"
    
    # шаблон структуры для массива errors
    error:
      title: error
      description: Структура элемента массива errors
      type: object
      properties:
        code:
          type: string
          description: Код ошибки
          example: Какой-то код ошибки
        message:
          type: string
          description: Описание ошибки
          example: Какое-то описание ошибки
    



