openapi: 3.0.2
info:
  title: Загрузка CSV с портфелем СБИ
  version: 1.0.0
  description: |

servers:
  - url: http://localhost:8080/v1
    description: Основной урл

tags:
  - name: employees
    description: Набор методов работы с сотрудниками

paths:
  /employees/search:
    post:
      tags:
        - employees
      summary: Поиск сотрудников
      description: |
        Чтение всех метаданных загруженных файлов с возможностью отбора и сортировки списка. 
        
        Поля, доступные для сортировки:
        >number, 
        
        >reportingDate, 
        
        >loadDate, 
        
        >fileName
      
      parameters:
        - $ref: "#/components/parameters/sortGetMetadata"
        # --> Шаблон. Стандартный набор параметров при чтении списка
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/offset"
        - $ref: "#/components/parameters/returnCount"
        - $ref: "#/components/parameters/returnOnlyCount"
        # <-- Шаблон.

      requestBody:
        description: |
          В теле передаются данные для фильтрации выборки. 
          **Content-type: application/json** используется только для визуализации тела запроса в SwaggerUI 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/employeesReq"  
          application/x-www-form-urlencoded:
            schema:  
              $ref: "#/components/schemas/employeesReq"
                    
      responses: 
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/employeesResp"
            application/x-www-form-urlencoded:
              schema:
                $ref: "#/components/schemas/employeesResp" 
                   
components:
  schemas:
    employeesObj:
      title: employeesObj
      type: object
      properties:
        department:
          type: string
        deskCodes:
          type: array
          items:
            type: string
        emailAlpha:
          type: string
        emailSigma:
          type: string
        firstName:
          type: string
        fullName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        objectId:
          type: string
        personalNumber:
          type: string
        phoneNumber:
          type: string
        positionName:
          type: string
        roles:
          type: array
          items:
            type: string
        spasId:
          type: string
        systemUser:
          type: boolean
        
    # схема запроса сотрудников
    employeesReq:
      title: employeesRequest
      type: object
      properties:
        request:
          type: object
          properties:
            filter:
              type: object
              properties:
                employeeId:
                  description: Массив идентификаторов сотрудников
                  type: array
                  items:
                    type: string
                    format: uuid
    
    # схема ответа на запрос сотрудников
    employeesResp:
      title: employeesResponse
      type: object
      properties:
        result:
          properties:
            listInfo:
              $ref: "#/components/schemas/resultFSP"
            items:
              type: array
              items:
                $ref: "#/components/schemas/employeesObj"
        errors:
          type: array
          items:
            $ref: "#/components/schemas/error"
        status:
          type: string
          example: SUCCESS / WARNING / ERROR
    
    # шаблон объекта listInfo для ответов на запросы с фильтрацией, сортировкой и пагинацией
    resultFSP:
      title: resultFSP
      type: object
      properties:
        limit:
          type: integer
        offset:
          type: integer
        count:
          type: integer

    # шаблон диапазона дат для фильтрации
    dateRangeTemplate:
      title: dateRangeTemplate
      type: object
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date

    # шаблон ответа. На бэке ППРБ3 формируется через класс ApiResponse
    responseTemplate:
      title: responseTemplate
      type: object
      properties:
        result:
          type: object
          #type: array
          #items:
          #  item
        errors:
          type: array
          items:
            $ref: "#/components/schemas/error"
        status:
          type: string
          example: SUCCESS / WARNING / ERROR
    
    # шаблон структуры для массива errors
    error:
      title: error
      description: Структура элемента массива errors
      type: object
      properties:
        code:
          type: string
          description: Код ошибки
          example: VALIDATION
        message:
          type: string
          description: Описание ошибки
          example: Какое-то описание ошибки
    
    # шаблон структуры справочника
    dictionary:
      title: dictionary
      description: Структура стандартного справочника
      type: object
      properties:
        code:
          type: string
          description: Идентификатор записи (первичный ключ)
        name:
          type: string
          description: Наименование элемента 
        nameEn:
          type: string
          description: Наименование элемента на английском языке

  parameters:
    limit:  
      name: limit
      in: query
      required: true
      description: Ограничение количества элементов в выборке. Значение - 0 - выбрать всё
      schema:
        type: integer
        format: uint
        minimum: 0
        example: 10
    
    offset:  
      name: offset
      in: query
      required: true
      description: Смещение страницы - 0, 1, 2 и т.д.
      schema:
        type: integer
        format: uint
        example: 0
      
    returnCount:  
      name: returnCount
      in: query
      required: false
      description: Указывается нужно ли возвращать общее количество элементов
      schema:
        type: boolean
        example: true
      
    returnOnlyCount:  
      name: returnOnlyCount
      in: query
      required: false
      description: Указывается нужно ли вернуть только количество элементов
      schema:
        type: boolean
        example: false

    sortGetData:
      name: sort
      in: query
      required: false
      description: В сортировке указываются направление сортировки(+/-) и имена полей через запятую.
      schema:
        type: string
        # Скорректировать пример для текущего метода ->
        example: +dealId,+dealName

    sortGetMetadata:
      name: sort
      in: query
      required: false
      description: В сортировке указываются направление сортировки(+/-) и имена полей через запятую.
      schema:
        type: string
        # Скорректировать пример для текущего метода ->
        example: -number